name: CI for Main Branch

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    name: Prebuild Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [ia32, x64]
        runtime: [electron]
        target: [13.1.6, 34.1.1]
    timeout-minutes: 30
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev linux-libc-dev
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v4
      - run: npm i
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild:ci -- --strip --runtime ${{ matrix.runtime }} --target ${{ matrix.target }} --arch ${{ matrix.arch }} -u ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild:ci -- --strip --runtime ${{ matrix.runtime }} --target ${{ matrix.target }} --arch x64 -u ${{ secrets.GITHUB_TOKEN }}
